# Generated by Django 6.0.7

from django.db import migrations

def populate_task_orders(apps, schema_editor):
    Task = apps.get_model('roadmap', 'Task')
    Phase = apps.get_model('roadmap', 'Phase')
    
    phases = Phase.objects.all().order_by('order')
    for phase in phases:
        tasks = Task.objects.filter(phase=phase).order_by('id')
        for idx, task in enumerate(tasks, start=1):
            task.order = idx
            task.save(update_fields=['order'])

class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_task_order'),
    ]

    operations = [
        migrations.RunPython(populate_task_orders, reverse_code=migrations.RunPython.noop),
    ]
