# Generated by Django 6.0.7 on 2026-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_rotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='assigned_person',
            field=models.CharField(blank=True, help_text='Person assigned to this task', max_length=100),
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='time',
            field=models.CharField(blank=True, help_text='Deadline or execution time, e.g., 14:00', max_length=50),
        ),
    ]
