# Generated by Django 6.0.7 on 2026-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_rotation', '0002_weeklytask_assigned_person_weeklytask_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team Member Name, e.g. Taiki', max_length=100)),
                ('email', models.EmailField(help_text='Email address for weekly role reminders', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Checked = Receives weekly Monday emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Recipient',
                'verbose_name_plural': 'Email Recipients',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Daily Cadence'), (2, 'Weekly Cadence'), (3, 'Bi-Weekly Cadence'), (4, 'Monthly Cadence'), (5, 'Ad-Hoc / Special')], default=1, verbose_name='Cadence Group'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='time',
            field=models.CharField(blank=True, help_text='Deadline or schedule time, e.g. 11:00 AM', max_length=50),
        ),
    ]
