# Generated by Django 6.0.7 on 2026-07-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='School Break', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Hex colour, e.g. #E63946', max_length=20)),
                ('bg', models.CharField(help_text='Background hex, e.g. #FFE0E3', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerSetting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('series_id', models.CharField(blank=True, help_text='Shared ID for recurring event series', max_length=50, null=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('start_time', models.CharField(blank=True, default='', help_text='e.g. 09:00', max_length=10)),
                ('end_time', models.CharField(blank=True, default='', help_text='e.g. 17:00', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.category', to_field='cat_id')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='scheduler.category', to_field='cat_id')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
